#!/usr/bin/env sh

sudo /opt/homebrew/bin/yabai --load-sa
/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

# global settings
/opt/homebrew/bin/yabai -m config mouse_follows_focus off
/opt/homebrew/bin/yabai -m config focus_follows_mouse off
/opt/homebrew/bin/yabai -m config window_origin_display default
/opt/homebrew/bin/yabai -m config window_placement second_child
/opt/homebrew/bin/yabai -m config window_topmost off
/opt/homebrew/bin/yabai -m config window_shadow on
/opt/homebrew/bin/yabai -m config window_opacity off
/opt/homebrew/bin/yabai -m config window_opacity_duration 2000.0
/opt/homebrew/bin/yabai -m config active_window_opacity 1.0
/opt/homebrew/bin/yabai -m config normal_window_opacity 0.85
/opt/homebrew/bin/yabai -m config window_border off
/opt/homebrew/bin/yabai -m config window_border_width 6
/opt/homebrew/bin/yabai -m config active_window_border_color 0xff775759
/opt/homebrew/bin/yabai -m config normal_window_border_color 0xff555555
/opt/homebrew/bin/yabai -m config insert_feedback_color 0xffd75f5f
/opt/homebrew/bin/yabai -m config split_ratio 0.50
/opt/homebrew/bin/yabai -m config auto_balance off
/opt/homebrew/bin/yabai -m config mouse_modifier fn
/opt/homebrew/bin/yabai -m config mouse_action1 move
/opt/homebrew/bin/yabai -m config mouse_action2 resize
/opt/homebrew/bin/yabai -m config mouse_drop_action swap

# general space settings
/opt/homebrew/bin/yabai -m config layout bsp
/opt/homebrew/bin/yabai -m config top_padding 00
/opt/homebrew/bin/yabai -m config bottom_padding 00
/opt/homebrew/bin/yabai -m config left_padding 00
/opt/homebrew/bin/yabai -m config right_padding 00
/opt/homebrew/bin/yabai -m config window_gap 05
# yabai -m config window_animation_duration    0.00
/opt/homebrew/bin/yabai -m rule --add app=".*" sub-layer=normal manage=off

# /opt/homebrew/bin/yabai -m rule --add app="^System Settings*" manage=off sub-layer=normal
# /opt/homebrew/bin/yabai -m rule --add app="^System Information$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Activity Monitor$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Finder$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Preview$" sub-layer=normal manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Alfred Preferences$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Feishu$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Lark$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Lark Meetings$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Seal$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^AppCleaner$" sticky=off sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Karabiner-Elements$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on sub-layer=above manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Things$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Spotify$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Outlook$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Microsoft Outlook$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Bartender 4$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^BetterTouchTool$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^WhatsApp$" is-floating=off sub-layer=normal
# /opt/homebrew/bin/yabai -m rule --add app="^Magnet$" manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^WeChat$" sub-layer=normal manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^QQ$" sub-layer=normal manage=off
# /opt/homebrew/bin/yabai -m rule --add app="^Music$" sub-layer=normal manage=off
/opt/homebrew/bin/yabai -m rule --add app="^iTerm2$" sub-layer=normal manage=on
/opt/homebrew/bin/yabai -m rule --add app="^Safari$" sub-layer=normal manage=on

# borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
yabai -m rule --apply
